### ISSUE TITLE
Possible issue with calculation

### ISSUE THREAD

**Issue by seekerkoruth** [antonmedv/expr#185] opened 2021-06-20 11:38 UTC
code:= `1+1/(4+5)*(1*5)+3.3+3.3+3.3+3.3/3.3*3.3`

When I run this code in excel, I get 14.7555. When I run it in expr, I get 14.2.

What accounts for the difference?

however this works:
`1.0+1/(4.0+5)*(1*5.0)+3.3+3.3+3.3+3.3/3.3*3.3`
yields
14.7555

It looks like you have to marshal the integers into floats by adding .0

Thank you.

**Comment by antonmedv** [comment] 2021-06-20 21:04
I think this can be an issue: 1/(4+5)*(1*5)

**Comment by seekerkoruth** [comment] 2021-06-21 12:05
How do you propose this can be solved? At the code level or at the end consumer level by adding the .0 hint to a literal numerator or denominator when there is division? However, if both the numerator and denominator are both variables then we may have less control.

**Comment by antonmedv** [comment] 2021-06-21 13:34
What about float as default for every constants in 1/2 expression?

**Comment by seekerkoruth** [comment] 2021-06-23 02:14
> What about float as default for every constants in 1/2 expression?

I think this will work. Float as a default for all division operation is a excellent rational solution to this issue.

**Comment by antonmedv** [comment] 2021-06-23 18:26
@davidklassen what do you think?

**Comment by mrxrsd** [comment] 2021-08-16 20:50
There are another issue related to precedence, I don't know if its the same root cause. 
The expression "-(1*2)^2" it is expected "-4" but it was returned "4".

**Comment by antonmedv** [comment] 2021-08-16 22:16
> The expression "-(1*2)^2" it is expected "-4" but it was returned "4".

Correct answer is -4.

**Comment by mrxrsd** [comment] 2021-08-16 22:23
Not according to google and wolfram alpha =p

https://www.wolframalpha.com/input/?i=-%281*2%29%5E2
https://letmegooglethat.com/?q=-(1*2)%5E2

**Comment by antonmedv** [comment] 2021-08-16 22:32
I guess unary op is higher priority than exponential in expr.

**Comment by antonmedv** [comment] 2022-11-05 19:17
Fixed in https://github.com/antonmedv/expr/commit/2aec311b2bcdb9ab5a8efee88c08138dde84a65c

**Closed by antonmedv** 2022-11-05 19:17 UTC
