### ISSUE TITLE
Avoid unneeded heap allocations in VM

### ISSUE THREAD

**Issue by deanm** [antonmedv/expr#55] opened 2019-08-18 21:12 UTC
https://github.com/antonmedv/expr/blob/a97d10e66a207bffb67f503fe58297fb14f3ee1c/vm/vm.go#L248

There are other similar heap allocations.  This could easily be replaced with a pre-allocated or stack allocated fixed array of some typical size, and if the callsite is bigger (if you happen to have some crazy number of arguments) then you could fall back to allocating.  Otherwise you are heap allocating on every call

**Comment by antonmedv** [comment] 2019-08-19 04:12
What is pre-allocates?

**Comment by deanm** [comment] 2019-08-19 07:55
Preallocated, meaning allocated before, not during the call

**Comment by antonmedv** [comment] 2019-08-19 08:03
But what is no call will occur? Sorry I don’t understand how this should work.

**Comment by deanm** [comment] 2019-08-19 08:47
#57

**Comment by antonmedv** [comment] 2020-02-25 12:24
Duplicate of #58

**Closed by antonmedv** 2020-02-25 12:24 UTC
