### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by seekerkoruth** [antonmedv/expr#187] opened 2021-06-23 12:28 UTC
Is there a way to timeout and kill a running expr.Run/VM.Run process if it is taking too long? This is to terminate/interupt runaway code that was miscoded,etc.  I did a string search for use of golang context and did not see any.

Thank you.

**Comment by seekerkoruth** [comment] 2021-06-23 12:52
I propose these code fragments:

```go
const shortDuration = 1 * time.Millisecond
d := time.Now().Add(shortDuration)
	ctx, cancel := context.WithDeadline(context.Background(), d)
	vm1:=expr.VM{}
	VM.Run(prg, env, ctx)

func (vm *VM) Run(program *Program, env interface{}, ctx ) (out interface{}, err error) {
	defer func() {
		if r := recover(); r != nil {
			f := &file.Error{
				Location: program.Locations[vm.pp],
				Message:  fmt.Sprintf("%v", r),
			}
			err = f.Bind(program.Source)
		}
	}()

	ctx, cancel := context.WithDeadline(context.Background(), d)
	var stopRunning=false
    
	go func(){
		
		select {
		case: <-ctx.Done():
			cancel()
			stopRunning=true
		}

	}()

	.
	.
	.


	vm.limit = MemoryBudget
	vm.ip = 0
	vm.pp = 0

	for vm.ip < len(vm.bytecode) {

		.
		.
		.
		if stopRunning{
			break;
		}
	}

```

**Comment by antonmedv** [comment] 2022-11-05 19:07
Duplicate of #260

**Closed by antonmedv** 2022-11-05 19:07 UTC
