### ISSUE TITLE
define expr global variables ?

### ISSUE THREAD

**Issue by AprilFiv** [antonmedv/expr#240] opened 2022-05-22 15:06 UTC
Can we set some variables into env and use them in custom functions?

**Comment by antonmedv** [comment] 2022-05-22 17:17
You can do it via method. Define custom func on env struct and access var from env.

**Comment by AprilFiv** [comment] 2022-05-23 02:13
> You can do it via method. Define custom func on env struct and access var from env.

thanks to replay.

**Comment by AprilFiv** [comment] 2022-05-23 02:15
> You can do it via method. Define custom func on env struct and access var from env.

Thanks to reply.  I mean if we use a custom func to set some variables, can we use them in another custom func?

**Comment by AprilFiv** [comment] 2022-05-23 02:18
> You can do it via method. Define custom func on env struct and access var from env.

I have known we could use env in script, I didn't notice any api of package to support custom function use env, may be a reference...

**Comment by antonmedv** [comment] 2022-11-05 18:55
I'm working on variables)

**Comment by antonmedv** [comment] 2022-11-05 18:56
Duplicate of #101

**Closed by antonmedv** 2022-11-05 18:56 UTC
Labels: enhancement
