### ISSUE TITLE
support slice to map builtin function?

### ISSUE THREAD

**Issue by forrestlinfeng** [antonmedv/expr#417] opened 2023-08-23 01:55 UTC
like this:
expr.Run("group(xxx, id)",   xxx)

input:  [
{ "id":  "key1",  "a"：123,  ”b“： ”abc“ }, 
{ "id":  "key2",  "a"：123,  ”b“： ”abc“ }
]
output {
    "key1" : { "id":  "key1",  "a"：123,  ”b“： ”abc“ },
    "key2" : { "id":  "key1",  "a"：123,  ”b“： ”abc“ }
}

**Comment by antonmedv** [comment] 2023-08-23 06:36
Duplicate of #162

**Closed by antonmedv** 2023-08-23 06:36 UTC
