### ISSUE TITLE
will expr  support operator  bit operation?

### ISSUE THREAD

**Issue by shuzhongling** [antonmedv/expr#338] opened 2023-02-23 10:23 UTC
expr is very powerful, but now it seems has not support the bit operation, such as go operator `&`, `|`, `<<`,  '>>' and so on.

will these operators will be supported in the future?

**Comment by antonmedv** [comment] 2023-02-23 10:27
Yes, it will be. I'm thinking to add support for pipes with `|` operator. So more likely bitwise will be added via some functions. (like in https://kotlinlang.org/docs/numbers.html#bitwise-operations)

Duplicate of #207

**Closed by antonmedv** 2023-02-23 10:27 UTC

**Comment by shuzhongling** [comment] 2023-02-25 14:10
thanks. but I think the bit operator operator has higher priority than the pipeline operator, because we can use the bit operator without remembering the function name. Almost all programmers know bit operators， such as `&`, `|`, `^` and so on. 
I want to use expr expression in the config file, it will do some data conversion, i hope the users don't need to remember the function name when they edit the config file.

**Comment by antonmedv** [comment] 2023-02-25 16:28
Expr already uses ^ operator as exponential.
And bringing it back to bitops will be a really big breaking change. I’d like to avoid doing so. 

So using alternative function names is one option. 

Another is to allow something like a special function  which treats ops differently 


    2^2 + bitops(0b001 ^ 2 | 8)
