### ISSUE TITLE
Another possibly v1.10 behavior change

### ISSUE THREAD

**Issue by zachaller** [antonmedv/expr#313] opened 2023-01-22 15:09 UTC
I think this is a fair representation of what we have in argo rollouts https://go.dev/play/p/03Krv5FFc9w

Stack trace from rollouts unit tests

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104ef559c]

goroutine 6 [running]:
testing.tRunner.func1.2({0x105aebbc0, 0x1066fe910})
	/Users/zaller/go/go1.19.5/src/testing/testing.go:1396 +0x374
testing.tRunner.func1()
	/Users/zaller/go/go1.19.5/src/testing/testing.go:1399 +0x560
panic({0x105aebbc0, 0x1066fe910})
	/Users/zaller/go/go1.19.5/src/runtime/panic.go:890 +0x26c
github.com/antonmedv/expr/checker.deref({0x0, 0x0})
	/Users/zaller/Development/argo-rollouts/vendor/github.com/antonmedv/expr/checker/types.go:207 +0x2c
github.com/antonmedv/expr/checker.(*visitor).IdentifierNode(0x140004fbdf8, 0x14000024b40)
	/Users/zaller/Development/argo-rollouts/vendor/github.com/antonmedv/expr/checker/checker.go:135 +0x21c
github.com/antonmedv/expr/checker.(*visitor).visit(0x140004fbdf8, {0x105cee5c8, 0x14000024b40})
	/Users/zaller/Development/argo-rollouts/vendor/github.com/antonmedv/expr/checker/checker.go:67 +0x368
github.com/antonmedv/expr/checker.(*visitor).BinaryNode(0x140004fbdf8, 0x14000024ba0)
	/Users/zaller/Development/argo-rollouts/vendor/github.com/antonmedv/expr/checker/checker.go:200 +0x58
github.com/antonmedv/expr/checker.(*visitor).visit(0x140004fbdf8, {0x105cee3d0, 0x14000024ba0})
	/Users/zaller/Development/argo-rollouts/vendor/github.com/antonmedv/expr/checker/checker.go:81 +0xbec
github.com/antonmedv/expr/checker.Check(0x140001389d8, 0x1400047d0a0)
	/Users/zaller/Development/argo-rollouts/vendor/github.com/antonmedv/expr/checker/checker.go:26 +0x18c
github.com/antonmedv/expr.Compile({0x1057e9c9c, 0xd}, {0x140004fc088, 0x1, 0x1})
	/Users/zaller/Development/argo-rollouts/vendor/github.com/antonmedv/expr/expr.go:164 +0x410
github.com/argoproj/argo-rollouts/utils/evaluate.EvalCondition({0x1059da340, 0x0}, {0x1057e9c9c, 0xd})
	/Users/zaller/Development/argo-rollouts/utils/evaluate/evaluate.go:80 +0x414
github.com/argoproj/argo-rollouts/utils/evaluate.EvaluateResult({0x1059da340, 0x0}, {{0x1057e1c7c, 0x3}, {0x0, 0x0}, {0x0, 0x0}, 0x0, {0x1057e9c9c, ...}, ...}, ...)
	/Users/zaller/Development/argo-rollouts/utils/evaluate/evaluate.go:23 +0x90
github.com/argoproj/argo-rollouts/metricproviders/datadog.(*Provider).parseResponse(0x140000c9220, {{0x1057e1c7c, 0x3}, {0x0, 0x0}, {0x0, 0x0}, 0x0, {0x1057e9c9c, 0xd}, ...}, ...)
	/Users/zaller/Development/argo-rollouts/metricproviders/datadog/datadog.go:155 +0x750
github.com/argoproj/argo-rollouts/metricproviders/datadog.(*Provider).Run(0x140000c9220, 0x140004a4b40, {{0x1057e1c7c, 0x3}, {0x0, 0x0}, {0x0, 0x0}, 0x0, {0x1057e9c9c, ...}, ...})
	/Users/zaller/Development/argo-rollouts/metricproviders/datadog/datadog.go:119 +0x7ec
github.com/argoproj/argo-rollouts/metricproviders/datadog.TestRunSuite(0x14000602b60)
	/Users/zaller/Development/argo-rollouts/metricproviders/datadog/datadog_test.go:321 +0xd48
testing.tRunner(0x14000602b60, 0x105cd3078)
	/Users/zaller/go/go1.19.5/src/testing/testing.go:1446 +0x174
created by testing.(*T).Run
	/Users/zaller/go/go1.19.5/src/testing/testing.go:1493 +0x540
```

**Comment by roqenrox** [comment] 2023-01-22 15:50
There is a difference between `nil` and `*T(nil)`. `expr` seems to take this into account (now). Your example code works if you get the type in the function `valueFromPointer`: https://go.dev/play/p/22qqmfcZb9R (line 42)

I don`t know if this is a bug of `expr` or of `valueFromPointer`.

**Comment by zachaller** [comment] 2023-01-22 16:26
I will try looking into this more tonight, just noticed the behavior change from 1.9 to 1.10 I will look into if there is something to fix in valueFromPointer if that is the more correct thing to do.

**Comment by antonmedv** [comment] 2023-01-22 18:40
I think I found the root cause.

```go
func TestCheck_works_with_nil_types(t *testing.T) {
	env := map[string]interface{}{
		"null": nil,
	}

	tree, err := parser.Parse("null")
	require.NoError(t, err)

	_, err = checker.Check(tree, conf.New(env))
	require.NoError(t, err)
}
```

This is just a bug new type checker. Will fix and release a new version.

**Comment by antonmedv** [comment] 2023-01-22 18:46
Fixed in 0675733cc8ab84586eba4b0c4a0c6c6348d8f0f0 (with a test to catch such errors) v1.10.3.

BTW, I'm thinking to add null coalescing operator `??`. So instead of default function, this can be used:

```
result ?? 1
```

What do you think?

**Comment by roqenrox** [comment] 2023-01-22 19:04
I'd appreciate a nil coalescing operator `??` very much.

**Comment by zachaller** [comment] 2023-01-22 20:42
Yea the nil coalescing sounds like a nice idea for sure, also will report v1.10.3 fixed the issue and argo-rollouts unit test are now passing 100% again so thank you for the quick fix and awesome lib

**Closed** 2023-01-22 21:36 UTC

**Comment by antonmedv** [comment] 2023-02-03 14:57
Nil coalescing is added in https://github.com/antonmedv/expr/releases/tag/v1.12.0 🔥
