### ISSUE TITLE
declare variable inside?

### ISSUE THREAD

**Issue by GunRyu** [antonmedv/expr#226] opened 2022-03-09 16:16 UTC
For expression like: `x = 5; x ** 2 + x` (it should be 5^2+5=30)

**Comment by antonmedv** [comment] 2022-03-09 16:25
I’m planning to add something like this.

**Comment by GunRyu** [comment] 2022-03-09 16:27
Cool!

**Comment by antonmedv** [comment] 2022-11-05 18:58
Duplicate of #101

**Closed by antonmedv** 2022-11-05 18:58 UTC
